CREATE TABLE IF NOT EXISTS users (
	username VARCHAR(50) PRIMARY KEY NOT NULL,
	password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
	id SERIAL PRIMARY KEY NOT NULL,
	category TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS subcategories (
	id SERIAL PRIMARY KEY NOT NULL,
	subcategory TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS styles (
	id SERIAL PRIMARY KEY NOT NULL,
	style TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS colors (
	id SERIAL PRIMARY KEY NOT NULL,
	color TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS patterns (
	id SERIAL PRIMARY KEY NOT NULL,
	pattern TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pieces (
    id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(255) REFERENCES users(username),
    categoryId INTEGER NOT NULL REFERENCES categories(id),
    subcategoryId INTEGER NOT NULL REFERENCES subcategories(id),
    styleId INTEGER NOT NULL REFERENCES styles(id),
    colorId INTEGER NOT NULL REFERENCES colors(id),
    patternId INTEGER NOT NULL REFERENCES patterns(id),
    imgFile VARCHAR(255) NOT NULL
);